# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('ip', models.GenericIPAddressField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
